# Generated by Django 2.0.7 on 2018-11-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price_schedule',
            field=models.CharField(help_text='Pricing model', max_length=50),
        ),
    ]
